package com.kurdistan.musicplayer;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import java.util.ArrayList;
import java.util.Collections;

public class MainActivity extends AppCompatActivity {
    private ArrayList<Artist> artists;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        artists = new ArrayList<>();
        insertTheSongs();
        Intent intent = new Intent(this, SongsActivity.class);
        startActivity(intent);
    }

    private void insertTheSongs() {
        ArrayList<Album> albums = new ArrayList<>();
        ArrayList<Song> songs = new ArrayList<>();
        Song song = new Song("Pearl", R.raw.pearl);
        songs.add(song);
        song = new Song("Fire", R.raw.fire);
        songs.add(song);
        song = new Song("Go", R.raw.go);
        songs.add(song);
        song = new Song("Khorasan", R.raw.khorasan);
        songs.add(song);
        song = new Song("Prism", R.raw.prism);
        songs.add(song);
        song = new Song("Circle", R.raw.circle);
        songs.add(song);
        song = new Song("You", R.raw.you);
        songs.add(song);
        song = new Song("The Centre", R.raw.the_centre);
        songs.add(song);
        song = new Song("Lament", R.raw.lament);
        songs.add(song);
        song = new Song("The Key", R.raw.the_key);
        songs.add(song);
        song = new Song("Jaaneh Jaanaan", R.raw.jaaneh_jaanaan);
        songs.add(song);
        song = new Song("Sari Gelin", R.raw.sari_gelin);
        songs.add(song);
        song = new Song("Khorasan (Arabic Version)", R.raw.khorasan_arabic_version);
        songs.add(song);

        Album album = new Album("The Centre", songs, R.drawable.sami_yusuf_the_centre);
        albums.add(album);
        songs = new ArrayList<>();
        song = new Song("Awake", R.raw.awake);
        songs.add(song);
        song = new Song("Ya Rasul Allah (Kurdish Version)", R.raw.ya_rasul_allah_p_1_kurdish_version);
        songs.add(song);
        song = new Song("Ya Rasul Allah", R.raw.ya_rasul_allah_pt_2);
        songs.add(song);
        song = new Song("Fiyyashiyya", R.raw.fiyyashiyya);
        songs.add(song);
        song = new Song("Ya Nabi", R.raw.ya_nabi);
        songs.add(song);
        song = new Song("Come See", R.raw.come_see);
        songs.add(song);
        song = new Song("Mast Qalandar", R.raw.mast_qalandar);
        songs.add(song);
        song = new Song("I Only Knew Love", R.raw.i_only_knew_love);
        songs.add(song);
        song = new Song("Lovers", R.raw.lovers);
        songs.add(song);
        song = new Song("Taha", R.raw.taha);
        songs.add(song);
        song = new Song("Ya Hayyu Ya Qayyum", R.raw.ya_hayyu_ya_qayyum);
        songs.add(song);
        song = new Song("Hamziyya", R.raw.hamziyya);
        songs.add(song);
        song = new Song("River of Milk", R.raw.river_of_milk);
        songs.add(song);
        song = new Song("Barakah", R.raw.barakah);
        songs.add(song);
        song = new Song("Mast Qalandar (Ft Rahat Fateh)", R.raw.mast_qalandar_ft_rahat_fateh);
        songs.add(song);
        song = new Song("Awake (Instrumental)", R.raw.awake_instrumental);
        songs.add(song);
        album = new Album("Barakah", songs, R.drawable.sami_yusuf_barakah);
        albums.add(album);
        Artist artist = new Artist("Sami Yusuf", albums);
        artists.add(artist);

        songs = new ArrayList<>();
        song = new Song("I Love You So", R.raw.i_love_you_so);
        songs.add(song);
        song = new Song("Number One for Me", R.raw.number_one_for_me);
        songs.add(song);
        song = new Song("Mawlaya", R.raw.mawlaya);
        songs.add(song);
        song = new Song("My Little Girl", R.raw.my_little_girl);
        songs.add(song);
        song = new Song("Forgive Me", R.raw.forgive_me);
        songs.add(song);
        song = new Song("One Big Family", R.raw.one_big_family);
        songs.add(song);
        song = new Song("Assalamu Alayka", R.raw.assalamu_alayka);
        songs.add(song);
        song = new Song("Paradise", R.raw.paradise);
        songs.add(song);
        song = new Song("Masha Allah", R.raw.masha_allah);
        songs.add(song);
        song = new Song("Radhitu Billahi Rabba", R.raw.radhitu_billahi_rabba);
        songs.add(song);
        song = new Song("Freedom", R.raw.freedom);
        songs.add(song);
        song = new Song("So Soon", R.raw.so_soon);
        songs.add(song);
        song = new Song("Muhammad (PBUH)", R.raw.muhammad);
        songs.add(song);
        song = new Song("Guide Me All The Way", R.raw.guide_me_all_the_way);
        songs.add(song);
        song = new Song("Mawlaya (Arabic Version)", R.raw.mawlaya_arabic_version);
        songs.add(song);
        song = new Song("Assalamu Alayka (Arabic Version)", R.raw.assalamu_alayka_arabic_version);
        songs.add(song);
        song = new Song("Radhitu Billahi Rabba (Arabic Version)", R.raw.radhitu_billahi_rabba_arabic_version);
        songs.add(song);
        albums = new ArrayList<>();
        album = new Album("Forgive Me", songs, R.drawable.maher_zain_forgive_me);
        albums.add(album);

        songs = new ArrayList<>();
        song = new Song("The Power (feat. Amakhono We Sintu)", R.raw.the_power_feat_amakhono_we_sintu);
        songs.add(song);
        song = new Song("Medina", R.raw.medina);
        songs.add(song);
        song = new Song("Peace Be Upon You", R.raw.peace_be_upon_you);
        songs.add(song);
        song = new Song("Good Day (feat. Issam Kamal)", R.raw.good_day_feat_issam_kamal);
        songs.add(song);
        song = new Song("By My Side", R.raw.by_my_side);
        songs.add(song);
        song = new Song("Jannah (English Version)", R.raw.jannah_english_version);
        songs.add(song);
        song = new Song("I'm Alive (feat. Atif Aslam)", R.raw.im_alive);
        songs.add(song);
        song = new Song("Allah Ya Moulana", R.raw.allah_ya_moulana);
        songs.add(song);
        song = new Song("Rabbee Yebarik (English Version)", R.raw.rabbee_yebarik_english_version);
        songs.add(song);
        song = new Song("True Love", R.raw.true_love);
        songs.add(song);
        song = new Song("Let It Go", R.raw.let_it_go);
        songs.add(song);
        song = new Song("The Way of Love", R.raw.the_way_of_love);
        songs.add(song);
        song = new Song("Close to You", R.raw.close_to_you);
        songs.add(song);
        song = new Song("One Day", R.raw.one_day);
        songs.add(song);
        song = new Song("Ummati (English Version)", R.raw.ummati_english_version);
        songs.add(song);
        album = new Album("One", songs, R.drawable.maher_zain_one);
        albums.add(album);
        artist = new Artist("Maher Zain", albums);
        artists.add(artist);
        Collections.sort(artists);
        ParentActivity.artists = artists;
    }
}
